### ISSUE TITLE
Can't load bcmdhd missing dtsi setup for ap2122

### ISSUE THREAD

**Issue by thevirtualdj** [BPI-SINOVOIP/BPI-M2U-bsp#6]
Can't load bcmdhd
downloaded fw (https://github.com/BPI-SINOVOIP/BPI-files/tree/master/others/brcm/lib/firmware/ap6212), can someone fex as in git source. 
"failed to power up DHD generic adapter".

**Comment by BPI-SINOVOIP** [comment]
Please get the fw from https://github.com/BPI-SINOVOIP/BPI_WiFi_Firmware/tree/master/ap6212 and place into /lib/firmware/ap6212, reboot and test.

**Comment by thevirtualdj** [comment]
in kernel .config it says fw_path="lib/firmware/bcm_dhd.bin which one should be used? fw_bcm43438a1.bin  or fw_bcm43438a0.bin or ?

**Comment by BPI-SINOVOIP** [comment]
kernel config file linux-sunxi/arch/arm/configs/sun8iw11p1smp_bpi_defconfig

`CONFIG_BCMDHD_FW_PATH="/lib/firmware/ap6212/fw_bcmdhd.bin"`
`CONFIG_BCMDHD_NVRAM_PATH="/lib/firmware/ap6212/nvram.txt"`

a0 and a1 will be detect by driver and load automatically.

thanks.
